[project]
name = "video-making"
version = "0.1.0"
description = "Slideshow and subtitle editor apps"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.10.2",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.16.0",
]
